@echo off
setlocal enabledelayedexpansion

REM Copies all files generated by the extractor to the necessary locations.
REM Run the extractor first (`./gradlew runServer`) before running this.

cd /d "%~dp0"

copy run\chunkedge_extractor_output\entities.json ..\crates\chunkedge_entity\extracted\
copy run\chunkedge_extractor_output\misc.json ..\crates\chunkedge_entity\extracted\
copy run\chunkedge_extractor_output\attributes.json ..\crates\chunkedge_generated\extracted\
copy run\chunkedge_extractor_output\blocks.json ..\crates\chunkedge_generated\extracted\
copy run\chunkedge_extractor_output\effects.json ..\crates\chunkedge_generated\extracted\
copy run\chunkedge_extractor_output\items.json ..\crates\chunkedge_generated\extracted\
copy run\chunkedge_extractor_output\packets.json ..\crates\chunkedge_generated\extracted\
copy run\chunkedge_extractor_output\sounds.json ..\crates\chunkedge_generated\extracted\
copy run\chunkedge_extractor_output\translation_keys.json ..\crates\chunkedge_lang\extracted\
copy run\chunkedge_extractor_output\registry_codec.json ..\crates\chunkedge_registry\extracted\
copy run\chunkedge_extractor_output\tags.json ..\crates\chunkedge_registry\extracted\
copy run\chunkedge_extractor_output\packets.json ..\tools\packet_inspector\extracted\
